-- On the PEPS user

CREATE OR REPLACE EDITIONABLE SYNONYM "PEPS"."SWD_PAGE_JURISDICTION" FOR "SWEETDEV"."SWD_PAGE_JURISDICTION";
CREATE OR REPLACE EDITIONABLE SYNONYM "PEPS"."SWD_PAGE" FOR "SWEETDEV"."SWD_PAGE";
CREATE OR REPLACE EDITIONABLE SYNONYM "PEPS"."SWD_PARAMETER" FOR "SWEETDEV"."SWD_PARAMETER";

-- On the SWEETDEV user
ALTER TABLE sweetdev.SWD_PARAMETER ADD (PARAMETER_DEFAULT_VALUE VARCHAR2(256 BYTE));
grant select on sweetdev.SWD_PAGE_JURISDICTION to peps;
grant select on sweetdev.swd_page to peps;